# Feuille de TP3 - Partie A : Manipulation de fonctions


In [1]:
# Import des modules
import numpy as np

**Attention :**
+ On rappelle que les noms de fonctions **ne doivent pas commencer par &laquo;_&raquo; ni contenir de caractères accentués** (plus précisément, les fonctions qui commencent par &laquo;_&raquo; ne peuvent pas être importées dans un autre module).
+ Les tableaux sont typées. Lorsque vous modifiez un élément d'une matrice, si les types sont différents, une conversion a lieu qui peut parfois engendrer des bugs... Voici un exemple pour illustrer cela.

In [2]:
A = np.array([[1,2], [3,4]])
print(A)
A[0,0] = 1.5 # 1.5 va être converti en entier !
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1.,2], [3,4]])

print(A)
A[0,0] = 1.5 # Pas de conversion
print(A)
print(type(A), type(A[0,0]))
A = np.array([[1,2], [3,4]], dtype=float)
print(A)
A[0,0] = 1.5
print(A)
print(type(A), type(A[0,0]))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'> <class 'numpy.int64'>
[[1. 2.]
 [3. 4.]]
[[1.5 2. ]
 [3.  4. ]]
<class 'numpy.ndarray'> <class 'numpy.float64'>
[[1. 2.]
 [3. 4.]]
[[1.5 2. ]
 [3.  4. ]]
<class 'numpy.ndarray'> <class 'numpy.float64'>


## Exercice 1 : Cryptographie basique : code de César (ou *Caesar cypher*)

Le principe de ce code est de "décaler" les lettres. Par exemple, si la clef choisie est 1, la lettre A sera remplacée par B, la lettre B par C, etc. Nous nous proposons ici de fabriquer une fonction de cryptage et de décryptage pour la clef 13.

#### a. <font color=red>Importer</font> le module `codecs` et tester les commandes `print(codecs.encode("abc", "rot+13"))` et `print(codecs.encode("abc", "rot-13"))` 

In [2]:
# Mettre votre code ici
import codecs
print(codecs.encode("abc", "rot+13"))
print(codecs.encode("abc", "rot-13"))

nop
nop


Comparer avec les 14, 15 et 16<sup>ème</sup> lettres de l'alphabet. 
#### b. Proposer une fonction `crypter()` qui demande à l'utilisateur de saisir une chaîne de caractères et affiche sa version codée.

In [8]:
# Mettre votre fonction ici
def crypter():
    ''' Demande de saisir un message puis affice sa version cryptée. '''
    mot =input('Choose a word')
    print("votre mot crypte est: ", codecs.encode(mot, "rot+13"))

crypter()

Choose a wordmitroglou
votre mot crypte est:  zvgebtybh


#### c. Ecrire une fonction `decrypter()` qui demande à l'utilisateur de saisir une chaîne de caractères encodée et affiche sa version décodée.

In [7]:
def decrypter():
    ''' Demande de saisir un message puis affice sa version cryptée. '''
    mot =input('Choose a word ')
    print("votre mot decrypte est: ", codecs.encode(mot, "rot+13"))
decrypter()

Choose a word nop
votre mot decrypte est:  abc


#### d.Tester la fonction `crypter()` avec un message déjà crypté. Expliquer le résultat (indice : il y a 26 lettres dans l'alphabet).


In [10]:
crypter() #decale de 13 lettres

Choose a wordzvgebtybh
votre mot crypte est:  mitroglou


## Exercice 2
### Question 1
A l'aide du module `numpy`, implémenter informatiquement la fonction $f : x \mapsto \sin(\pi x)$.

In [23]:
def sinusPI(x):
    return np.sin(np.pi*x)
sinusPI(1)

1.2246467991473532e-16

### Question 2
Ecrire une fonction qui convertit une vitesse depuis des $km/h$ vers des miles par heure puis des noeuds. On rappelle que 1 mile = 1609 m et 1 noeud $= 0.514 m.s^{-1}$. 

In [27]:
def KmtoMile(x):
    mile = x/1.609
    return mile
def Kmtoneouds(x):
    mtokm=0.514*3.6
    return x/mtokm

Kmtoneouds(5)

2.7021184608733244

### Question 3

   1. Ecrire une fonction qui prend en argument un tableau et renvoie un tableau de même taille rempli par le nombre à virgule flottante $3.0$ .
   2. A l'aide de la fonction numpy `isscalar` écrire une fonction qui prend un argument `x` et renvoie $3.0$ si `x` est un scalaire et un tableau de $3.0$ s'il s'agit d'un tableau.

In [38]:
def fonctionaupif(x):
    return 3*np.ones(len(x))
fonctionaupif([1,2,3,4])

array([3., 3., 3., 3.])

In [42]:
def test(x):
    if isscalar(x):
        return x
    return 3*np.ones(len(x))
    
    

### Question 4
L'aire d'un triangle peut être calculée à partir des coordonnées de ses trois sommets par la formule :
\begin{equation*}
 	\mathcal{A} = \frac{1}{2}\big\vert (x_1 - x_3)(y_2-y_1)  - (x_1-x_2)(y_3 - y_1) \big \vert
\end{equation*}
Ecrire une fonction qui prend comme argument un tableau bi-dimensionnel dont chaque ligne est la coordonnée $(x,y)$ d'un sommet et renvoie son aire.

In [ ]:
def aire(tab):
    return 1/2(absolute[0][0]) # a ecrire
    

### Question 5
Ecrire une fonction qui prend en argument un tableau et remplace ces coefficients strictement positif par $1$ et ses coefficients strictement négatifs par $-1$.

In [45]:
def Changement(tab):
    return np.where(np.array(tab)<0, -1,1)

Changement([-100,10,10,-10,10,10])

array([-1,  1,  1, -1,  1,  1])

## Exercice : comparaison de nombre flottants

Le module `scipy.linalg' contient des fonctions classiques d'algère linéaire. En particulier, il fournit les fonctions :
   * `inv` qui prend en argument une tableau de dimension 2  correspondant à une matrice carrée et qui renvoie son inverse (s'il existe),
   * `norm` qui prend un vecteur est renvoie sa norme 2 (par défaut) et qui fonctionne aussi pour des matrices (voir l'aide pour connaître les normes possibles),
   * solve qui prend en argument un tableau de dimension 2 représentant une matrice $A$ et un tableau de dimension 1 représentant un vecteur $v$ et cherche à résoudre Ax=b.

1. Importez le module `scipy.linalg` comme `slin`, définissez une matrice $A$ (si possible inversible) et un vecteur $u$. Calculez le déterminant de $A$, inversez la matrice, calculez $x=A^{-1}u$, puis calculez la norme de $Ax-u$. Comparer $Ax$ et $u$.
2. Testez également la commande `allclose` pour comparer $Ax$ et $u$.
3. Recommencez en résolvant le système linéaire par la commande `solve`.

In [ ]:
# Mettre ici votre code pour la question 1.
import scipy.

In [ ]:
# Mettre ici votre code pour la question 2.

In [1]:
# Mettre ici votre code pour la question 3.

# Exerice : itérer une fonction

1 . Ecrire une fonction `itere` :

* qui prend en argument une fonction `f` (représentant une fonction mathématiques $f : x \in \mathbb{R} \mapsto f(x)$, un réel $x$ et un entier $n$,
* qui renvoie l'itérée n-ième de $f$ en x (*ie* $f^n (x) = f\circ\big(f^{n-1}(x)\big) = f\circ f \circ f \dots f(x)$)

2. Tester la fonction itere pour $f_a x \mapsto 0.5*(\frac{x}{a} - x)$ et $a=11$ puis $a=3$ et différentes valeurs de $n$.

3. Remarque que pour $a>0$, $f_a(x)=x$ si et seulement si $x = \sqrt(a)$. Ecrire alors un fonction `itere_seuil` qui :
    * qui prend en argument une fonction `f` (représentant une fonction mathématiques $f : x \in \mathbb{R} \mapsto f(x)$, un seuil `epsilon` et un réel `x`,
    * l'argument $x$ pourra être pris égal à 1 par défaut,
    * qui renvoie l'itérée n-ième de $f$ en x (*ie* $f^n(x)$) où $n$ est le plus petit entier tel que $\vert(f^{n+1}(x)-f^n(x)\vert \leqslant \varepsilon$.
    
Tester pour la même fonction $f$ que précédement et $\varepsilon = 1e-6$ et $a = 3$ et 11.

4. Afin d'éviter une boucle infinie, ajouter un nombre maximum d'itération. Ce nombre pourra être de $10^6$ par défaut. La fonction devra de plus renvoyer le nombre d'itération faites.
 Tester votre condition d'arrêt pour $x \mapsto 2 x$.